### ISSUE TITLE
Line directives / pragmas not supported

### ISSUE THREAD

**Issue by traveltissues** [camfort/fortran-src#100]
As far as I can tell there no support for pragmas in the AST at the moment. Would these additions be welcome?

```
#line 6 '/path/to/file.f'
```
https://www.cenapad.unicamp.br/parque/manuais/Xlf/lr208.HTM
https://docs.oracle.com/cd/E19957-01/805-4939/z4000733204e/index.html

EDIT:
on second thought, adding this is probably madness since it seems to work somewhat like an inverse `INCLUDE` without expansion (it modifies an [error report location for example](https://github.com/camfort/fortran-src/issues/100#issuecomment-481648444)) and would mean splicing blocks in existing trees to insert such a node. More specifically the line directive creates an association of source code in different literal locations as a single logical source.  The `#line` directive seems to only be supported by xlf; I didn't find a reference to this in any standard and apparently it's technically a preprocessor directive only not a language feature. thoughts @mrd ?

**Comment by traveltissues** [comment]
on second thought, adding this is probably madness

**Comment by traveltissues** [comment]
cc @lukaszkolodziejczyk

**Comment by traveltissues** [comment]
```
# 6 "/path/to/some/other/file.f"
       PROGRAM LINE_DIR_ERROR
         SYNTAX ERROR
         PRINT *, "Output"
       END
```
reports a syntax error on line 7 for example

**Comment by mrd** [comment]
It's a useful pragma for dealing with the output of preprocessors so I think there is merit.

I think these things are usually handled by the lexer. It's possible that the filename field of `aiPosition` could be updated after encountering one of these lines.

**Comment by mrd** [comment]
I've pushed a test branch that implements this idea in the Fixed Form lexer

https://github.com/camfort/fortran-src/tree/line-pragma

test:

          PROGRAM LINE_DIR_ERROR
    #line 6 "somefile.f"
    c     comment
          PRINT *, 'Output'
          END


This does raise some questions, for example: it is now possible to have source spans that begin in one file and end in another, and I don't touch the absolute offset field at all, which may be just as well.

**Comment by ruoso** [comment]
I think it would be important to make a distinction of the span as found in
the file read versus the span as indicated by the line directive, tho.

That would allow for better reasoning on cases like the one you mentioned...

**Comment by mrd** [comment]
Yes, that's probably the best for functionality. I've switched it to a different field `posPragmaOffset`, which contains the difference between the line in the concrete file and the apparent line in the pragma. This way both can be tracked by changes in the regular `posLine` field.

**Comment by mrd** [comment]
added to 9de6d8e8f9ac6513fd9de61a393502f870c2aaad
