### ISSUE TITLE
INCLUDE statements not parsed

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#11]
```   
      program foo
      implicit none
      include 'bar.cmn'
      end  
````

This is part of Fortran 90 (see p.43 of the standard, ftp://ftp.nag.co.uk/sc22wg5/N001-N1100/N692.pdf)
However, it seems fairly common to use this in Fortran 77 too.... although it is not standard. Perhaps we can allow it in Fortran 77 extended mode?

**Comment by dorchard** [comment]
I propose, for the moment, that we create a 'permissive mode' F77 parser (using CPP is probably easiest) which adds a production for `INCLUDE` to the grammar. Then we can generate two parsers:
Fortran77 and Fortran77Permissive (the later of which we can use with some of our corpus, which is F77 but has includes).

**Comment by madgen** [comment]
That already exists it it called Fortran77Extended. There is no way of selectively adding rules to one but not the other though. So for INCLUDE it will just be an overgenerating parser.

Keep in mind F90 already supports INCLUDE.

**Comment by dorchard** [comment]
I suggested using CPP so that we can selectively add rules to one but not the other.

**Comment by madgen** [comment]
Ohhhh, I see. That's a good idea but it requires some thinking because every divergent production needed to be generated twice and all productions that have divergent productions on RHS also need to be generated with two names, etc. Do you mind leaving this open until Monday and we can discuss in the meeting and I can start implementing right away?

**Comment by dorchard** [comment]
Sure. That'd be great. I don't follow what you are saying about generating twice / two names though. I was thinking that for INCLUDE we could get away with having an additional case for `NONEXECUTABLE_STATEMENT` that is wrapped in an `#ifdef` block. We can then generate two `.y` files (with some #ifdef on the module/parser names).
