### ISSUE TITLE
FORMAT statement does not work

### ISSUE THREAD

**Issue by FulgurIgor** [camfort/fortran-src#110]
I have tried to parse the next code:
```fortran
      program main
      print 9000
 9000 FORMAT('HELLO, WORLD!')
      end program main
```
but fortran-src is failed with the following error:
```
ProgramFilefortran-src: fortran-src: user error (test.F, 4:23: test.F: parsing failed. 
Last parsed token: TId (4:11)-(4:22) "programmain".)
```

I have run it as: `fortran-src -v Fortran77Extended test.F`

**Comment by madgen** [comment]
`end program main` is Fortran 90 onwards but the program is in fixed form. We don't have support for that. See #109.

**Comment by FulgurIgor** [comment]
> end program main is Fortran 90 onwards but the program is in fixed form. We don't have support for that. See #109.

Wow! Thanks! I did not know that it is Fortran 90 feature. 

But the reprinter returns this code as:
```fortran
      program main
      print 9290
9290  format ('hello,world!')
      end
```
It removes spaces in format string...

And, if FORMAT statement is in several lines, reprinter produces one long line, that is not appropriate to fixed form.

**Comment by madgen** [comment]
Ah, that's a bug can you make a separate issue about that. We should definitely fix that.
