### ISSUE TITLE
Build instructions in README.md

### ISSUE THREAD

**Issue by uranix** [camfort/fortran-src#118]
I would like to try fortran-src to do some analysis on a big legacy Fortran project. Unfortunately I'm not a Haskell programmer and I don't know how to produce a runnable executable given Setup.hs and package.yaml. 

It would be highly appreciated if README.md had some instructions how to do this on a clean Ubuntu machine, for example.

**Comment by madgen** [comment]
`fortran-src` has an executable for debugging and inspection, but it is really meant to be used as a library in an Haskell project.

If you would like to build an executable nonetheless, it is enough to install [stack](https://docs.haskellstack.org/en/stable/README/)  and clone the project.

Run the following to build the project
```
stack setup
stack build
```

To run it use
```
stack exec -- fortran-src
```

**Comment by uranix** [comment]
That was instant, thank you! Do you mind if I add this to the readme file?

**Comment by madgen** [comment]
No problem, I just added them to the README. Glad I could help.
