### ISSUE TITLE
CASE statements on multiple values fail to parse (Fortran 90)

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#12]
Example program:
```
program foo
  implicit none
  integer :: i = 0
  select case(i)
  case(0,1)
     WRITE (*,*) "0 or 1"
  case default
     WRITE (*,*) "anything else"
  end select
end program
```

Looking at the parser this does seem to be accounted for, so I'm not sure why it is failing.
Error is:
` ProgramFileforpar: 5:10: Parsing failed.Last parsed token: TComma (5:9,5:9). `

**Comment by madgen** [comment]
again, working on my end. I suspect you're using the wrong version of the parser.

**Comment by dorchard** [comment]
Ok. I have the latest version built, but I'll try a `stack clean; stack build`

**Comment by madgen** [comment]
No, I have handled this weeks ago. It is not an old version issue.
