### ISSUE TITLE
Inconsistent AST node for label

### ISSUE THREAD

**Issue by madgen** [camfort/fortran-src#13]
Fortran 90 parser uses ValInteger while Fortran 66/77 parsers use ValLabel. I'd like to eliminate ValLabel altogether and at some point it should become an annotation.

I can't do this at this point because there are five instances in BBlocks that I don't know if they are safe to remove or what. If they can be changed to ValInteger please let me know.

**Comment by mrd** [comment]
I'm only interested in extracting and using the label itself. I don't care if it is a ValLabel or a ValInteger. It seems like the 5 instances you mention are all pattern-matching to extract the label. So you should be able to just change them, search and replace.
