### ISSUE TITLE
BBlocks analysis produces refuted pattern for some kinds of nested

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#14]
```
module test
  implicit none
  contains
   
   subroutine foo 
     integer:: i, j

     do i = 1, 2
        do j = 1, 2
        end do
     end do
 
   end subroutine
   
end module
```
Via camfort's stencil analysis, this throw up the error:
```
$ camfort stencils-infer test.f90 out
...
camfort: src/Language/Fortran/Analysis/BBlocks.hs:39:47-82: Irrefutable pattern failed for pattern Just gr
``

**Comment by dorchard** [comment]
Looks like @mrd's code, but maybe @madgen is able to fix too.

**Comment by dorchard** [comment]
Strangely the error goes away if you remove one level of `do` on the inside.

**Comment by madgen** [comment]
I checked the parse tree, it is parsed correctly.

**Comment by dorchard** [comment]
The latest round of commits by @mrd now fixes the above problem. I am getting the following error now though which may be a related problem:
```
module foo
   implicit none

   contains

   subroutine bar(x)
     integer x
   end subroutine
   
end module
```
gives
```fortran-src: src/Language/Fortran/Analysis/BBlocks.hs:481:5-84: Irrefutable pattern failed for pattern mainEntry : _```
If there are no arguments to the subroutine it is fine though.
