### ISSUE TITLE
ValInteger should not have an annotation

### ISSUE THREAD

**Issue by madgen** [camfort/fortran-src#16]
Value nodes are meat to be embedded in ExpValue at all times, hence none of them need annotation. Enclosing expressions should have the annotations.

At some point @mrd changed this for ValVariable (I believe for renaming), it would be nice if we go back to original design as right now all captures/generations of ValIntegers end up copying the same annotation for ValVariable and its enclosing ExpValue.

**Comment by mrd** [comment]
in commit c3eea28749d86acdfe95f7402b87887060c1c978
