### ISSUE TITLE
The feature Output graph seems not work.

### ISSUE THREAD

**Issue by 0xzhang** [camfort/fortran-src#169]
I use option "--dot", but the output not in DOT format. And option "-o FILE" also not work.

**Comment by raehik** [comment]
`--dot` makes it so that if the command you've selected will print a graph, that graph will be output in DOT format. The default action is to parse and print the raw AST, so writing `--dot` there won't do anything. Could I confirm that you're running a command like `fortran-src --supergraph --dot $FILE`? I'll need a little more information to help if that's not the problem.

**Comment by 0xzhang** [comment]
> `--dot` makes it so that if the command you've selected will print a graph, that graph will be output in DOT format. The default action is to parse and print the raw AST, so writing `--dot` there won't do anything. Could I confirm that you're running a command like `fortran-src --supergraph --dot $FILE`? I'll need a little more information to help if that's not the problem.

Thanks for your reply. According your advice, I use command `fortran-src --supergraph --dot $FILE` and get the DOT output. According `fortran-src --help`, I have tried `fortran-src --dot $FILE`  and it still print a raw AST, no DOT format.

Option `-o FILE` don't work expectedly. So I use `>` write output to a file.

The `--help` is not same as I think. I hope I can use appropriate command :)

**Comment by raehik** [comment]
> Thanks for your reply. According your advice, I use command `fortran-src --supergraph --dot $FILE` and get the DOT output. I have tried `fortran-src --dot $FILE` and it print a raw AST, no DOT format. I get a pdf of the AST.

This sounds about right. The default action is to parse the input file and pretty-print the AST to stdout. However, as you found out:

> Option `-o FILE` don't work expectedly. So I use `>` write output to a file.

`-o` doesn't work for redirecting pretty-printed ASTs or graphs. You're right, the `fortran-src` CLI offers lots of options that sound generic, but are actually only used for certain commands. I might make an issue for this, since I just recently implemented a neat & tidy CLI for another project and could do the same here. I'm not too sure how much use the `fortran-src` CLI tool gets though, so it depends!

> But I found the AST maybe not correct corresponding to source code. Like `COMMON /ZZZ/ Z(1)` will be parsed to "`call Z`".

This sounds suspiciously familiar to the function call/array indexing ambiguity. If you could share some code or an example that shows what you mean, I could maybe help.

**Comment by 0xzhang** [comment]
```fortran
      SUBROUTINE TEST
      INTEGER A
      COMMON /KAN/ A(2)
      END
```
In above code, I declare a array `A(2)` in common block. But `A(2)` will be parsed to a `ExpFunctionCall` in second `BlStatement`.
```
ProgramFile (MetaInfo
                     {miVersion = Fortran77,
                      miFilename = "new.f"})
            [PUSubroutine ()
                          (1:7)-(4:9)
                          (Nothing, Nothing)
                          "test"
                          Nothing
                          [BlStatement ()
                                       (2:7)-(2:15)
                                       Nothing
                                       (StDeclaration ()
                                                      (2:7)-(2:15)
                                                      (TypeSpec ()
                                                                (2:7)-(2:13)
                                                                TypeInteger
                                                                Nothing)
                                                      Nothing
                                                      (AList ()
                                                             (2:15)-(2:15)
                                                             [DeclVariable ()
                                                                           (2:15)-(2:15)
                                                                           (ExpValue ()
                                                                                     (2:15)-(2:15)
                                                                                     (ValVariable "a"))
                                                                           Nothing
                                                                           Nothing])),
                           BlStatement ()
                                       (3:7)-(3:23)
                                       Nothing
                                       (StCommon ()
                                                 (3:7)-(3:23)
                                                 (AList ()
                                                        (3:14)-(3:23)
                                                        [CommonGroup ()
                                                                     (3:14)-(3:23)
                                                                     (Just ExpValue ()
                                                                                    (3:14)-(3:18)
                                                                                    (ValVariable "kan"))
                                                                     (AList ()
                                                                            (3:20)-(3:23)
                                                                            [ExpFunctionCall ()
                                                                                             (3:20)-(3:23)
                                                                                             (ExpValue ()
                                                                                                       (3:20)-(3:20)
                                                                                                       (ValVariable "a"))
                                                                                             (Just AList ()
                                                                                                         (3:22)-(3:22)
                                                                                                         [Argument ()
                                                                                                                   (3:22)-(3:22)
                                                                                                                   Nothing
                                                                                                                   (ExpValue ()
                                                                                                                             (3:22)-(3:22)
                                                                                                                             (ValInteger "2"))])])]))]
                          Nothing]

```

**Comment by raehik** [comment]
Yeah, this is related to the ambiguity between function calls and array indices:

  1. In `Parser/Fortran77.y`, the `COMMON_NAME` rule uses `ELEMENT`, which uses `SUBSCRIPT`, which maps all `var(x)` to `ExpSubscript`s -- which is *correct*, but
  2. after parsing we rewrite certain subscripts to function calls, and it looks like these common group names get caught (occurs in `Disambiguate.Function.disambiguateFunctionCalls`).

I wonder if common groups should be treated a bit more like declarations/type specs? That would apparently avoid this issue, but I don't know if common group syntax is more complex than that. @dorchard any thoughts?

**Comment by 0xzhang** [comment]
[COMMON (FORTRAN 77 Language Reference)](https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7v/index.html)
This is a reference from Oracle. 
```fortran
COMMON [/[cb]/] nlist [[,]/[cb]/ nlist]
```
As descript in reference, `nlist` is **List of variable names, array names, and array declarators**. There should be no more complicated syntax.

**Comment by raehik** [comment]
Thanks for that. We're likely parsing common blocks wrong, since we're parsing expressions instead of declarations. That would prevent function call/array index ambiguity from occurring in the first place too. We don't appear to use `StCommon` much either, so it wouldn't be a big change outside of the parser.

I'll make a separate issue for tracking that. @0xzhang can I close this issue if the output graph problem was solved?

**Comment by 0xzhang** [comment]
@raehik Yes, I already know the answer. Thank you for your patient help. Hopefully one day I'll be able to read these Haskell code and find the problem :smiley:
