### ISSUE TITLE
Rewriter Bug: '!' character in string literals treated as an explicit comment

### ISSUE THREAD

**Issue by envp** [camfort/fortran-src#179]
While examining chunks, [`evaluateChunks_`](https://github.com/camfort/fortran-src/blob/37fe7b2005ff1bc1f4abec1020a783ce50b10666/src/Language/Fortran/Rewriter/Internal.hs#L194-L237) is too eager in determining where an explicit comment starts.

This is due to using `(BC.elemIndex '!' chStr)` will trip up on `!` characters inside string literals, and report that Sourcelocation as the start of an explicit comment.

The right way to go about this would be:
1. Traverse each chunk, while maintaining state about whether a character is in a string literal or not
2.  Use this state  to locate a `!` outside a string literal

The code in question lives here:

https://github.com/camfort/fortran-src/blob/37fe7b2005ff1bc1f4abec1020a783ce50b10666/src/Language/Fortran/Rewriter/Internal.hs#L209-L211

E.g.:

```
      write(8, *) "a really long string!", var1, var2, var3
                                       ^
                                       |__ `nextLen` points to here
```

**Comment by raehik** [comment]
This is an irritating by-product of text-based rewriting. I grappled with it before when [adding a continuation reformatter](https://github.com/camfort/fortran-src/pull/129#issuecomment-767697093) (adds continuations for long lines). We can already do the necessary lexing, and have a framework for writing changes directly to an AST (in [CamFort](https://github.com/camfort/camfort) however), but the whole setup is too fragile to work for all use cases.

Regardless, fixes are welcome. Thanks for noticing this!
