### ISSUE TITLE
`fromJust` exception for subroutines without their definition in scope

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#18]
This could relate to issue #14. I am getting a `fromJust` exception coming out of the following piece of code called with `fortran-src -S fun.f90`

```
program fun
  implicit none
  integer :: x

  call someSUB(x)

  if (.true.) then
    x = someFUN(x)
  end if

end program fun
```

**Comment by dorchard** [comment]
Actually, this is not the problem. I have reduce it down a bit more. The issue is (possible reasonably) when calling subroutines that don't exist:
```
program fun
  implicit none
  integer :: x
  
  call someSUB(x)
 
end program fun
```

**Comment by mrd** [comment]
Yep, it's functions or subroutine that don't exist.

A better error message is warranted, I suppose.

**Comment by dorchard** [comment]
It seems okay with functions, but I guess it's because they haven't been disambiguated from arrays?

**Comment by dorchard** [comment]
This bug strangely went away recently but now appears to be back (possibly with recent changes to the super graph building code)? We really need to be able to get round this.

**Comment by dorchard** [comment]
I can confirm that, if you don't build the supergraph this `fromJust` exception is not reached. In Camfort, in the stencil specs. inference part, if I just look at the graph associated to each program unit this goes away, but converting to the new supergraph raises this exception, so I suppose the problem is somewhere around the interaction of stitching and undefined functions/subroutines.

**Comment by mrd** [comment]
Well yeah. What do you mean the bug went away? Undefined functions are undefined functions. I can't do anything about the fact that they don't exist.

**Comment by dorchard** [comment]
Generating a `flowsGraph` for individual program units with undefined cals does not raise an error. Generating a `flowsGraph` from the supergraph of a program with undefined calls, raises `fromJust` somewhere.

**Comment by mrd** [comment]
Right, because the supergraph must look up every function and subroutine call by its nature -- it's interprocedural analysis.

Doing only intraprocedural analysis does not require looking up other functions or subroutines.

**Comment by dorchard** [comment]
Ok. Can we just treat an unknown subroutine/function as a no-op for the moment.  We can work to do cross-file interprocedural analysis later- but I think even if we can't find the definition in another file, for the sake of many of our analyses we want to just pass over it.

**Comment by dorchard** [comment]
This has been dealt with and there is some better error reporting now in analysis code.
