### ISSUE TITLE
[ Question ] Use fortran-src in Ubuntu 18.04

### ISSUE THREAD

**Issue by deniseiras** [camfort/fortran-src#212]
Hi !
fortran-src binaries of all versions are not compatible with glibc of Ubuntu 18.04.
I also tried to compile, then get some errors (to be posted soon, I lost them), when using version 0.9 (tried stack and cabal - recomended version) and version 0.5. (cabal). I used ghcup for installing this compilers.

Is there a way to use the latest versions of fortran-src in Ubuntu 18.04 ?

Best
Denis

**Comment by raehik** [comment]
Thanks, I didn't know about glibc. That's a pain for distributing "magical" binaries.

My virtual machine is struggling, but I *think* I'm succeeding in building it. I had to `apt install libgmp-dev`! (I think GitHub's VMs come with it installed already, so I hadn't realized.)

**Comment by raehik** [comment]
@deniseiras did you have any luck with installing `libgmp-dev` before compiling?

**Comment by deniseiras** [comment]
> @deniseiras did you have any luck with installing `libgmp-dev` before compiling?

Hi Ben,

Sorry for the late reply. I replyed via email, but it didnt appear here. Because I am not a superuser on a server, my solution was use an singularity container with a 20.04 distro and works !

I also tried on my computer - 18.04 distro. I Installerd libgmp-dev, and ...

`
denis@denis-dell:/dados/_COM_BACKUP/inpe/AvaliacaoQualidadeCoreDin/tools/camfort_fortran_src$ ./fortran-src 
./fortran-src: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./fortran-src)
`

Many thanks for the advances,
Denis

**Comment by raehik** [comment]
That's a pain. You need `libgmp-dev` to build, or a prebuilt binary for your distro, and we only build for the latest Ubuntu. But glad you got it working!

**Comment by deniseiras** [comment]
Hi Ben,

Sorry for the late reply. Because I am not a superuser on a server, my
solution was use an singularity container with a 20.04 distro.
Many thanks for this solution, I really appreciate it.

*--*
*Abs,*
*Denis*





Em seg., 21 de mar. de 2022 às 09:48, Ben Orchard ***@***.***>
escreveu:
