### ISSUE TITLE
Flow analysis seems incorrect when inside modules. 

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#22]
There appears to be some problems with building flows graphs (and other related information) when working inside subroutines/functions inside a Fortran 90 module. I have extended [DataFlowSpec.hs](https://github.com/camfort/fortran-src/blob/master/test/Language/Fortran/Analysis/DataFlowSpec.hs)
with a module-subroutine-Fortran90 version of the `loop4` test. I don't expect the block numbers to be the same, but the flows graph is clearly now a different shape. Also there are some `fromJust` exceptions getting thrown up in some cases.

**Comment by dorchard** [comment]
Sorry, scrap the last part, the `fromJust` exceptions are due to something else in the test, not your code.

**Comment by mrd** [comment]
Yeah, modules won't be in the BBlockMap because modules don't have basic blocks, only subroutines, functions and programs do.

**Comment by dorchard** [comment]
I think that commit https://github.com/camfort/fortran-src/commit/b58adbaa4a4bc70121bbc486af4482b176019df9 fixed this.
