### ISSUE TITLE
Failure to parse array and union access in lhs of `StExpressionAssign`.

### ISSUE THREAD

**Issue by RaoulHC** [camfort/fortran-src#238]
The following code seems to throw off part of the analysis:
```fortran
      program main
      structure /t_foo/
        union
          map
            integer bar(5)
          end map
          map
            integer*2 baz(10)
          end map
        end union
      end structure
      record /t_foo/ foo
      foo.bar(1) = 2
      end program main
```
which when run with `fortran-src -v77l struct.f` outputs
```
ProgramFilefortran-src: Use of varName on non-variable.
CallStack (from HasCallStack):
  error, called at src/Language/Fortran/Analysis.hs:180:72 in fortran-src-0.10.2-C80sJplqHvQBdeJnK28qPz:Language.Fortran.Analysis
```
Other usages of `foo.bar(1)` don't seem to throw it off so I presume the analysis does something specifically for `StExpressionAssign`.

Tested on current master 1251b4e

**Comment by raehik** [comment]
Yeah, this is weird. On a quick check, `varName` is being called with `ExpDataRef` somewhere in the type analysis. Only the assignment statement is required to reproduce the issue:

```fortran
      program main
      foo.bar(1) = 2
      end program main
```

**Comment by mrd** [comment]
My guess is line 247 of Types.hs

**Comment by raehik** [comment]
That's it -- `foo.bar(1)` is `ExpSubscript (ExpDataRef (ExpValue (ValVariable "foo")) (ExpValue (ValVariable "bar")))`. Calling `varName v` where `ExpSubscript _ _ v_` seems dangerous.

Adding an equation to `varName` fixes the exception:

```haskell
-- | Obtain either uniqueName or source name from an ExpValue variable.
varName :: Expression (Analysis a) -> Name
-- ...
-- | Recursively apply to the left for data refs e.g. @var%field@ -> @var@
varName (ExpDataRef _ _ e _) = varName e
-- ...
```

fortran-src has shaky struct/custom type support -- for Raoul's program, the type analysis labels `foo` as both a `TCustom` custom type and a `CTFunction`. But this does solve the crash!

**Comment by raehik** [comment]
For posterity, this bug appears to have existed since at least 2021-08-31 (that's the oldest binary I have lying around).
