### ISSUE TITLE
Nested labeled DO loops can't be grouped when sharing final statement

### ISSUE THREAD

**Issue by madgen** [camfort/fortran-src#26]
```fortran
      SUBROUTINE A
        DO 42 I = 1,10
          DO 42 J = 1,10
            STOP
 42     CONTINUE
      END
```

**Comment by madgen** [comment]
Given the recursive grouping function will always group the inner most block, there needs to be a clause that checks the last statement of each group (which is luckily stored for other reasons) for a corresponding label.

Another approach is to realise the same label is seen multiple times, but this is trickier as it requires communication between different stack frames...

**Comment by dorchard** [comment]
This is still in a bad state. We now allow this, but it get's partially grouped into something which is not equivalent:
```
      SUBROUTINE A
        DO 42 I = 1,10
          DO J = 1,10
            STOP
 42     CONTINUE
         END DO
      END
```
I am looking into the easiest way to back out of the grouping do avoid this.

**Comment by madgen** [comment]
Could you next time work on a separate branch if you know your commit is introducing a bug?

**Comment by dorchard** [comment]
I didn't realise it was a bug until now.

**Comment by dorchard** [comment]
After more discussion, we should be able to group here. Any inability to group should be reported as an error.

**Comment by madgen** [comment]
8efa004dac2a9443cdc53a1d12608e2b8d3f632c fixed this.
