### ISSUE TITLE
Support scalefactor on variable name 

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#28]
```
      program scale
      character a*8
      end
```
We currently don't support this, but it is in the Fortran 77 standard.

**Comment by dorchard** [comment]
Related to this,  we do allow `character*8 a` in F77 mode, but not in F90 mode. But in F90 mode we allow `character a*8` but not `character*8 a`! I believe both variants are allowed in each spec.

**Comment by madgen** [comment]
ftp://ftp.nag.co.uk/sc22wg5/N001-N1100/N692.pdf

Checkout 5.1
