### ISSUE TITLE
Add Ord instances

### ISSUE THREAD

**Issue by Boarders** [camfort/fortran-src#282]
It would be helpful to add derived Ord instances to almost all types so they can be used in standard containers such as `Data.Set`. I'd be happy to do this if the idea seems palatable.

**Comment by raehik** [comment]
Thanks @Boarders . Sensible and adds a bit of convenience, I see no major reason not to. (Compilation time is a concern, but it doesn't seem to have an outrageous impact.) We should note that AST `Ord` instances don't guarantee any specific behaviour, other than being a valid instance. I've pushed a PR over at #283 .

**Comment by Boarders** [comment]
Thanks, that is very helpful! I'm not sure if this would make more sense as a request after the modules have been split up slightly (if compilation times are the worry), but it may make sense at some point to also add `Hashable` and `NFData` (though I would say those are less important)

**Comment by dorchard** [comment]
https://github.com/camfort/fortran-src/pull/283 is now merged for a new release 0.16.1. Does that satisfy the issue at hand suitably?

**Comment by raehik** [comment]
Closing as resolved as I'm confident #283 is what @Boarders had requested.

**Comment by Boarders** [comment]
That's correct - thanks both!
