### ISSUE TITLE
Prelude.read: no parse on reals with no leading 0

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#31]
I think this error is coming from fortran-src to do with the real-parsing functionality though it appears when I am using camfort (e.g., `units-infer` or something). Example
```
program f
   implicit none
   real :: x = .1
end program
```
camfort fails with
`camfort: Prelude.read: no parse`

**Comment by mrd** [comment]
Yes.. that's why I've been asking around for a function that reads Fortran
literals.

We have the definition within the lexer, but it is not interpreted as a
number.

**Comment by madgen** [comment]
It shouldn't be interpreted as a number in the source tree. An external routine is probably the best option.

**Comment by mrd** [comment]
What do you mean by external? It doesn't have to be interpreted as a number in the source tree, but if I'm going to write a function that follows the literal rules of Fortran grammar, where else would I put it but in fortran-src?

**Comment by madgen** [comment]
Yeah, yeah. I meant not stored in the AST.

**Comment by mrd** [comment]
I believe that it is possible to reuse Alex for this purpose, as I'd rather not drag in another dependency on a regex library, and anyway it's best to share the same definition as the regular lexer. So I'll look into it later.

**Comment by mrd** [comment]
BTW, this should have been a bug in camfort since the specific call to 'read' was in camfort.

And it's fixed now.
