### ISSUE TITLE
IVMAP only getting partially built

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#36]
Example program:
```
program foo
  implicit none
  integer :: i, j
  real, dimension(100) :: a, b
  do i=1,100
     do j=1,100
        a(i) = b(i) + b(1)
     end do
  end do
end program
```
At some point in the last month (I think), a bug has been introduced which means that the induction-variable analysis is wrong. See `fortran-src -S foo.90`:
```
...
ivMap: fromList [(5,fromList ["foo_j2"])]
```
`i` is missing.

**Comment by mrd** [comment]
Closed in 4b98e35
