### ISSUE TITLE
Fortran 95 support.

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#37]
We do not yet have a Fortran 95 parser.

**Comment by harry-clarke** [comment]
95 Spec: http://j3-fortran.org/doc/standing/archive/007/97-007r2/pdf/97-007r2.pdf
*1.5.1: Fortran 90 Compatibility:*
- [ ] Remove real and double precision Do variable support (Parser).
- [ ] Remove branching to ENDIF statement from outside its IF construct (tricky, as may need context).
- [ ] Remove PAUSE statement (Parser).
- [ ] Remove ASSIGN statement (Parser).
- [ ] Remove assigned GOTO statements (may not need to do anything, but need to check, as don't know all of the use cases).
- [ ] Remove assigned format specifiers (may not need to do anything, but need to check, as don't know of the use cases).
- [ ] Remove the H edit descriptor (need to look at how we currently parse format specifiers).

*Additional Tasks:*
- [ ] Allow functions to be declared "pure".
- [ ] Allow functions to be declared "elemental".
- [ ] Add FORALL parsing.
- [ ] 4.1.1: Add component initialisation, related to NULL

**Comment by dorchard** [comment]
Sorted by 57b5b5e44f94df155a0d8ad14aa336c45ddf237f
