### ISSUE TITLE
Empty 'if' block causes exception

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#41]
For example
```
program emptyIf
  implicit none
  if (.true.) then
  end if

end program emptyIf
```
throws up:
```
$ fortran-src EmptyIf.f90 
ProgramFilefortran-src: Trying to find how long an empty list spans for.
CallStack (from HasCallStack):
  error, called at src/Language/Fortran/AST.hs:500:17 in main:Language.Fortran.AST
```

**Comment by madgen** [comment]
That's a bug to be fixed, but kudos to past me who wrote an error message that immediately explains where the problem occurs.

**Comment by dorchard** [comment]
I think it occurs when doing `getTransSpan` inside of the grouping. I've seen this before actually. There is a small fix.
