### ISSUE TITLE
Grouped array subscript

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#42]
I've noticed some code using an array subscript a bit like the following:
```
program arra
  integer, dimension(5) :: x
  integer :: i
  x([1,2,5]) = 42
end program
```
This assigns to 1, 2 and 5 indices at the same time. I haven't found which standard (if any) introduces this. But I suspect it's Fortran 95.

**Comment by madgen** [comment]
[] is normally used for coarrays. But I don't think that is it. It might be non-standard.

**Comment by dorchard** [comment]
Yeah it isn't a coarray. I've skimmed through 95, 2003, and 2008 and still can't find it. It works in gfortran. I wonder where it has come from...!

**Comment by mrd** [comment]
Fortran 2003 defines delimiters `[ ... ]` being equivalent to `(/ ... /)`, therefore the example shown above is a 'vector subscript' of an array. In this case that means it would be the equivalent of writing `x(1)=42`, `x(2)=42`, and `x(5)=42` on separate lines.
