### ISSUE TITLE
dataFlowSolver exception

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#43]
The code in `computational-physics-1/fortran77/code214.f` raises a dataFlowSolver exception that I can't debug, see:  ```fortran-src code214.f -S```

**Comment by dorchard** [comment]
The error here has gotten much better:
```
$ fortran-src computational-physics-1/fortran77/code214.f -S
fortran-src: An unexpected LHS to an expression assign: ExpFunctionCall () (42:8)-(42:14) (ExpValue () (42:8)-(42:12) (ValVariable "ranf")) Nothing
CallStack (from HasCallStack):
  error, called at src/Language/Fortran/Analysis.hs:239:16 in main:Language.Fortran.Analysis
```
It seems there is some syntactic construct which we are not expecting where line 42 is:
`        RANF() = ISEED/FLOAT(IC)`
(this is inside the definition of the function `RANF`). This is possibly non-standard Fortran so it is not our fault- but we should check the Fortran 77 standard to see if this is allowed or not.

**Comment by mrd** [comment]
I think that it might be a typo.. Check out code213.f

**Comment by traveltissues** [comment]
does #72 close this?

**Comment by mrd** [comment]
I'm 100% certain this was a typo in code214.f, nothing to do with us.

      FUNCTION RANF()
      DATA IA/16807/,IC/2147483647/,IQ/127773/,IR/2836/
      COMMON /CSEED/ ISEED
        IH = ISEED/IQ
        IL = MOD(ISEED,IQ)
        IT = IA*IL-IR*IH
        IF(IT.GT.0) THEN
          ISEED = IT
        ELSE
          ISEED = IC+IT
        END IF
        RANF() = ISEED/FLOAT(IC)
      RETURN
      END

whereas the same exact function (but for one change) in code213.f:


      FUNCTION RANF()
      DATA IA/16807/,IC/2147483647/,IQ/127773/,IR/2836/
      COMMON /CSEED/ ISEED
        IH = ISEED/IQ
        IL = MOD(ISEED,IQ)
        IT = IA*IL-IR*IH
        IF(IT.GT.0) THEN
          ISEED = IT
        ELSE
          ISEED = IC+IT
        END IF
        RANF = ISEED/FLOAT(IC)
      RETURN
      END
