### ISSUE TITLE
Fortran 95 should support ending an interface with a name

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#56]
Fortran 95 standard allows an `end interface` to be named (matching the start of the interface block); see p.213 (absolute) of http://j3-fortran.org/doc/standing/archive/007/97-007r2/pdf/97-007r2.pdf

Strangely, it appears that this is not in the Fortran 90 standard.... (http://docs.cray.com/books/007-3692-003/html-007-3692-003/dcdalchri.html#ZFIXEDYGVZP8PQ see section 2.5.11) so we should add this into the Fortran95 parser.

Example:
```
module testing
  interface named
     subroutine foo(arg)
       real :: arg
     end subroutine foo
  end interface
end module testing
```
(`test/Language/Fortran/samples/interface.f90`).

**Comment by mrd** [comment]
I think this was sorted in November but the comment at the end of the line still causes a problem as referenced in another bug report. Will deal with that separately.
