### ISSUE TITLE
Fortran 95 should allow PURE and ELEMENTAL prefixes in function and subroutine statements

### ISSUE THREAD

**Issue by jme52** [camfort/fortran-src#62]
The structure of function and subroutine statements is defined in sections 12.5.2.2 and 12.5.2.3 of the Fortran 95 standard, respectively (https://wg5-fortran.org/N1151-N1200/N1191.pdf, see pages 226-228 of the pdf).  In particular, for functions,
> R1217 _function-stmt_ **is** [ _prefix_ ] FUNCTION _function-name_ ( [ _dummy-arg-name-list_ ] ) [ RESULT ( _result-name_ ) ]
> [...]
> R1218 _prefix_ **is** _prefix-spec_ [ _prefix-spec_ ] ...
> R1219 _prefix-spec_ **is** _type-spec_ **or** RECURSIVE **or** PURE **or** ELEMENTAL

and for subroutines

> R1222 _subroutine-stmt_ **is** [ _prefix_ ] SUBROUTINE _subroutine-name_ [ ( [ _dummy-arg-list_ ] ) ]
> Constraint: The _prefix_ of a _subroutine-stmt_ shall not contain a _type-spec_.

While the `RECURSIVE` _prefix-spec_ seems well supported (probably because it was already part of the Fortran 90 standard, see R1217 in absolute page 189 of https://wg5-fortran.org/N001-N1100/N692.pdf), the `PURE` and `ELEMENTAL` prefixes, which were introduced in the Fortran 95 standard, produce parsing errors.

I will copy below some problematic examples and the output they produce when running camfort 0.905 with fortran-src 0.2.1.1.

**Comment by jme52** [comment]
Example (pure function, _prefix_ with only one _prefix-spec_):
```
module mpf2

contains

   pure function pf(a)
      integer, intent(in) :: a
      integer :: pf
      pf = a * 2
   end function

end module
```
Parsing error:
```
$ stack exec camfort count pf2.f90 
Counting variable declarations in 'pf2.f90'
pf2.f90, 5:8: pf2.f90: parsing failed. 
Last parsed token: TPure (5:4)-(5:7).
```

**Comment by jme52** [comment]
Example (elemental function, _prefix_ with two _prefix-spec_ s):
```
module mef

contains

   elemental integer function ef(a)
      integer, intent(in) :: a
      ef = a * 2
   end function

end module
```
Parsing error:
```
$ stack exec camfort count ef.f90 
Counting variable declarations in 'ef.f90'
ef.f90, 5:13: ef.f90: parsing failed. 
Last parsed token: TElemental (5:4)-(5:12).
```

**Comment by mrd** [comment]
Sorry for neglecting this issue. It should have been fixed this past month. However I should note that part of the problem is that your files end with the extension .f90, which tells fortran-src to default to using the Fortran90 parser. I have recently added a more convenient way to override the default, with an option such as -F95, that will work in both camfort and fortran-src.

**Comment by jme52** [comment]
Thank you for the fix and for adding the `-F95` flag.

Concerning the fact that extension `.f90` was part of the problem, note that the extension of the files os not part of the standard.  Hence, I would like to point you to a blog post written a few years ago by the current convenor of ISO/IEC/JTC1/SC22/WG5, and former Intel's Doctor Fortran, Steve Lionel https://software.intel.com/en-us/blogs/2013/01/11/doctor-fortran-in-source-form-just-wants-to-be-free .  In this article, Lionel discusses that `.f90` was adopted as an extension for free-form code, as opposed to the `.f` extension of existing fixed-form code, but that there is no expectation that the number after the `f` denotes the version of the Fortran standard the file follows - after all, modern versions of the standard continue to allow fixed-form syntax, and adhering to a standard + ISO TR or TS would be difficult to encode in an extension.

Note also that at least one of the most widely used Fortran compilers (Intel) does not support extensions such as `.f95`, `.f03`, etc., so these extensions are and should be avoided by developers who want their Fortran programs to be portable.

I think that assuming that `.f90` files are Fortran 90 files is not what Fortran developers will assume - the `-F95` flag is great, but I would recommend it is easier to find, and that for `.f90` files you consider making the default Fortran version the last version you fully support, not Fortran 90.
