### ISSUE TITLE
Cannot parse one-armed-if with assignment to array.

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#7]
```
program simple
  implicit none
  integer, dimension(1) :: x
  if (.true.) x(1) = 1
end program simple
```
fails with:
``ProgramFileforpar: 4:15: Lexing failed. Last parsed token: TRightPar (4:13,4:13).``

Can't track down why this is. The parsing for an `if` with just the "true" branch seems fine. A possible shift/reduce problem? Doesn't appear for assignments to non-arrays or assignments to arrays with multi-armed `if`.

**Comment by dorchard** [comment]
The current fix only works for Fortran 77, but not Fortran 90. The above program breaks with the same error for Fortran 90 mode.

**Comment by madgen** [comment]
It works for Fortran 90 on my end. If you have a new example, please submit here.

**Comment by dorchard** [comment]
The above program does not work for me (as `simple.f90` to trigger Fortran 90 parse)
