### ISSUE TITLE
Add a reference to file containing token in Language.Fortran.Utils.Position

### ISSUE THREAD

**Issue by vaibhav-y** [camfort/fortran-src#79]
I have a suggestion for changing `Language.Fortran.Utils.Position`, so that it includes a reference to the file. This would be useful when processing `StInclude`s so that notable events from within the included file are reported with the correct file path.

My suggestion is to have map of file to file-ids, that is passed updated with seen files while building the AST, and `Position` to hold the file id corresponding to the file the token was seen in. 

I think that having the file path as a part of the error would be beneficial for diagnostics reporting.

What are your thoughts on this?

**Comment by madgen** [comment]
This seems to be useful only for the includes, which is a good enough justification now that we have some support for them.

I don't see why we need a map from files to file-ids though. Is there a case in which the file belonging to an id needs to be updated throughout the AST?

@mrd thoughts?

**Comment by vaibhav-y** [comment]
The file ids is primarily for efficiency sake, storing a integer in each AST node instead of the full string which remains fixed throughout the run. As for files updated through the AST, I think it could be convenient for source to source transformations

cc: @traveltissues @ruoso

**Comment by mrd** [comment]
Such strings would likely be shared structure in Haskell since they all come from the same place.

**Comment by mrd** [comment]
Closed in #80.
