### ISSUE TITLE
Dimension declaration inside COMMON statements

### ISSUE THREAD

**Issue by lukaszkolodziejczyk** [camfort/fortran-src#86]
Consider the following code:

```
      integer range1,
     +        multi1
      common /comm1/ range1(2:5),
     +               multi1(12, 10:16),
     +               range2(30:40),
     +               multi2(26, 50:60)
      integer range2,
     +        multi2
```

Dimension declarations for `range1`, `multi1`, `range2` and `multi2` inside the above COMMON statement will become `ExpSubscript` in AST, which sounds quite right.

On contrary, in the following code:
```
      integer*2 stkind1
      integer simple1, nonstkind1*2
      common /comm2/ stkind1(2),
     +               simple1(4),
     +               nonstkind1(6),
     +               stkind2(18),
     +               simple2(20),
     +               nonstkind2(2)
      integer*2 stkind2
      integer simple2, nonstkind2*2
```
All dimension declarations will become `ExpFunctionCall` in AST which seems to be a bug.
Shouldn't the AST generation be amended to tag these dimensions declaration with `ExpSubscript` in every above case?

**Comment by mrd** [comment]
I think this was resolved a while back.
